# Generated by Django 3.2 on 2021-04-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmodel',
            name='good',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snsmodel',
            name='read',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snsmodel',
            name='readtext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
