# Generated by Django 3.2 on 2021-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snsapp', '0003_auto_20210418_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snsmodel',
            name='readtext',
            field=models.TextField(blank=True, default='default', null=True),
        ),
    ]
